### ISSUE TITLE
Decide where to host

### ISSUE THREAD

**Issue by bradgarropy** [remix-austin/new-remixaustin-com#10]
**DECISION: Cloudflare**

**Comment by sethdavis512** [comment]
What are the team's thoughts on SPA for now? We could host right here using GH pages. Thoughts?

https://www.youtube.com/watch?v=EO_-KwSslWQ

**Comment by bradgarropy** [comment]
I would figure SEO is important to us for discoverability of the meetup, so SPA wouldn't be a great choice. Vercel has free Remix hosting options that would give us SSR.

https://vercel.com/docs/frameworks/remix

**Comment by sethdavis512** [comment]
I'm down. Who should own the account? @brookslybrand?

**Comment by bradgarropy** [comment]
I would assume either Shopify or Remix have an existing pro account that we could leverage.

**Comment by sethdavis512** [comment]
Ooh let's do that - great thinking

**Comment by eduardoroliveira** [comment]
Have you guys used Cloudflare? I am using the free layer for my personal site and works great so far...  https://www.cloudflare.com/plans/
[Our Plans | Pricing | Cloudflare](https://www.cloudflare.com/plans/)
Discover which Cloudflare plan is correct for your requirements. Find out more about Cloudflare plan pricing and sign up for Cloudflare here!

**Comment by brookslybrand** [comment]
I'd prefer to avoid Remix or Shopify owning the account, just to avoid "playing favorites" with the meetup I help organize.

Also, we definitely don't have a Vercel account 😆

Right now we're using Fly and spending less than $5 a month, so the fee gets waved. We could also try Cloudflare, they have a generous free tier as well. Vercel is also fine and easy

Doesn't matter who owns the account, depending on the host we can setup an org and give access to the accounts that makes sense

**Comment by bradgarropy** [comment]
Then in that case I would prefer Cloudflare over Fly simply because Cloudflare offers a built in solution for continuous deployment.

**Comment by sethdavis512** [comment]
I'll vote for Cloudflare as well...to be honest, haven't used it - would like to be familiar with it

**Comment by bradgarropy** [comment]
I'm good with hosting on Cloudflare. I've got the site hooked up in my Cloudflare account, and I'll make the required changes to run on the Cloudflare platform in an upcoming PR.
