### ISSUE TITLE
Create skeleton routes

### ISSUE THREAD

**Issue by bradgarropy** [remix-austin/new-remixaustin-com#12]
![image](https://github.com/remix-austin/new-remixaustin-com/assets/11336745/cd1d36a4-3e8f-4ecf-b13d-25efbec3cb88)

```
/
/blog
/blog/:slug
/talks
/talks/:slug
/welcome
```

I'm not exactly sure what the `Welcome form with Google Form API` means. Do we have that form created? What is its purpose?

**Comment by sethdavis512** [comment]
> Do we have that form created? What is its purpose?

Yeah this is the form that Brooks uses to get attendance/info from people ("Are you looking for a job" etc) at the beginning of the meetups.

**Comment by sethdavis512** [comment]
I think that bullet is basically having the actual form on RemixAustin.com and then posting the results to Goog

**Comment by bradgarropy** [comment]
Yea, might as well do a real `<form>` instead of linking out to Google Forms. We _are_ all web developers here 😆

**Comment by brookslybrand** [comment]
> @brookslybrand do you have a link to that Google Form?

https://docs.google.com/forms/d/e/1FAIpQLSf85bzda4hx_TZvMhAhq3V9KD19NiWhJQAVauMZYLEqXVRhWA/viewform?usp=send_form
